---
apiVersion: v1
kind: Service
metadata:
  name: svc-demo-api
  namespace: demo-product-dev
  annotations:
    metallb.universe.tf/address-pool: v2-int
    metallb.universe.tf/allow-shared-ip: allow-for-demo
spec:
  selector:
    app: demo-api
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-demo-api
  namespace: demo-product
  annotations:
    metallb.universe.tf/address-pool: v2-int
    metallb.universe.tf/allow-shared-ip: allow-for-demo
spec:
  selector:
    app: demo-api
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
